version: '3.8'

services:
  db:
    image: postgres:17.4-bookworm
    environment:
      - POSTGRES_DB=ai_todo
      - POSTGRES_USER=ai_todo_user
      - POSTGRES_PASSWORD=pass
    ports:
      - "15432:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "4200:4200"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=ai_todo_user
      - DB_PASSWORD=pass
      - DB_NAME=ai_todo
      - DB_SSLMODE=disable
    command: sh /app/entrypoint.sh
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./client:/app
      - ./docs:/docs
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    stdin_open: true
    tty: true